### ISSUE TITLE
Exclude from voicing 

### ISSUE THREAD

**Issue by MuratovAS** [Danesprite/tts-util-app#17]
It would be nice if it were possible to exclude a voice from reading: 
- URL
- Tags (#)
- Emoji

I think that such options can be made in the settings.

**Comment by Danesprite** [comment]
This is a good idea.  I'll see what I can do.

Spasibo.  :-)

**Comment by Danesprite** [comment]
Another text element that might be useful to exclude is the parenthetical
statement.  This would be off-by-default, of course.

**Comment by Danesprite** [comment]
I have taken some time to look into this today.

Tags (#) are easy enough to filter out, of course.  Doing the same for URLs doesn't look too difficult.  The only question is which types of URL to filter.  Filtering URLs with the HTTP (and HTTPS) scheme and the mailto scheme seems good enough to my mind.  That covers most hyperlinks.

For emoji, it is too difficult, since the application would need to parse through the relevant Unicode "data file" and compare input bytes.  I'm not really willing to put the time into that.  I will say that, although some text-to-speech engines (e.g. eSpeak and Google TTS) read out descriptions of each emoji encountered, others just pass over them silently.  The older Android app for the CMU Flite TTS engine does this, for instance.  It is available from the F-Droid store [here](https://f-droid.org/en/packages/edu.cmu.cs.speech.tts.flite).

I'll add options for the first two in the next version.

**Comment by Danesprite** [comment]
This feature is now available in *TTS Util* version 4.0.0.  See the [releases page](https://github.com/Danesprite/tts-util-app/releases/tag/v4.0.0).  The new version will be available on the Google Play and F-Droid stores soon.
