### ISSUE TITLE
tts-util-app is a keyboard that will be cool

### ISSUE THREAD

**Issue by Pantyhose-X** [Danesprite/tts-util-app#21]
hello Danesprite
 I would like to have tts-util-app Function keyboard

Applied to language learning. Pronunciation correction
Learning a foreign language. Example Russian German I don't know how to speak, TTS taught me to speak
Text-to-Speech Always speak typed keys speak Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.

example，
l only want to talk when you press keys on the keyboard, not to read the screen
https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback

https://user-images.githubusercontent.com/42504385/132130706-a1a8ec10-416a-4711-b5d3-c91086e9710f.mp4

https://www.youtube.com/watch?v=YPBn6D6pf78&t=207s

https://user-images.githubusercontent.com/42504385/127757873-c3c076d3-ce73-40b1-8f57-423459fc0c2f.MP4

l only want to talk when you press keys on the keyboard, not to read the screen

**Comment by Danesprite** [comment]
Hello @Pantyhose-X,

Thank you for opening this issue.

The feature you mention and provide demo videos for is indeed quite a useful
one.  I can certainly see its value as a language studies aid.  However, re-
implementing it in TTS Util may be rather difficult and, since it is already
present in talkback, counter-productive.

If I may ask, since this feature is already available to you in talkback and
Word, what use have you for it in my application?

For what it's worth, character-by-character reading may already be achieved
in TTS Util by delimiting the input characters with spaces or newlines.  I
would not be against adding a more convenient spelling mode for this in the
application settings. I think this would be a separate issue, however, since
reading the whole input field is not what you have in mind.

Kind regards,
Dane Finlay

**Comment by Pantyhose-X** [comment]
hello @Danesprite talkback He reads all your actions aloud. talkback is a screen reader.
`We only need to read the keyboard out loud and not anything else aloud`. talkback and [NVDA](https://github.com/nvaccess/nvda) cannot do that.

**Comment by Danesprite** [comment]
Oh, I see what you mean.  Well, it looks like this won't be too difficult
to implement after all.  The application need only use a *TextWatcher*
implementation for its input fields to read new text on key presses.

I might have this implemented in the next version (3.1.0).  It may not be
as smooth as the screen reader solutions, (I have not the resources of
Google,) but it will be closer to what you have in mind.

**Comment by Danesprite** [comment]
Hello @Pantyhose-X,

I thought I would let you know that I have implemented the playback-on-
input feature.

The next version of *TTS Util* will be released in the next few days.  This
feature (disabled by default) will be available in that version via the
option in the settings screen.

**Comment by Danesprite** [comment]
This feature is now available in *TTS Util* version 4.0.0.  See the [releases page](https://github.com/Danesprite/tts-util-app/releases/tag/v4.0.0).  The new version will be available on the Google Play and F-Droid stores soon.

Sorry this took more longer than a few days, @Pantyhose-X.

**Comment by Pantyhose-X** [comment]
@Danesprite TTS can't method read aloud the input of other applications 🙁
It is recommended to make IME keyboard software, TTS only needs to read aloud the keyboard input

Input Method Editor
You can base
* https://github.com/florisboard/florisboard Apache-2.0 license
* https://github.com/google/mozc   BSD-3-Clause license

**Comment by Danesprite** [comment]
Hello @Pantyhose-X,

I thought I had made this point clear above; the feature only works in
*TTS Util* input fields, not in all input fields in general.  I am not
willing to expose this function with a custom IME; it would be a lot of
work and is simply not a good fit for my application.

I suggest you pursue the florisboard issue you opened on this subject
last year (florisboard/florisboard#391) if the new *TTS Util* playback-
on-input feature is really not what you need.
