### ISSUE TITLE
Read text from text dialog ends with blank screen

### ISSUE THREAD

**Issue by kudlav** [Danesprite/tts-util-app#28]
Hi, text context menu doesn't work when selecting text on webpages in Firefox. I  opens this screen and nothing is played.

TTS Util 4.0.0
Android 11
SM-A405FN

![Screenshot_20220814-085054_TTS Util](https://user-images.githubusercontent.com/11516259/184525927-35b4cf7d-eee5-4bb9-a211-e870e0504d27.png)

**Comment by Danesprite** [comment]
Hello Vladan,

Thank you for reporting this problem.  I have been able to reproduce it on
an Android 11 device running TTS Util version 4.0.0.  The same behaviour
occurs when using the 'Read text' share menu entry or the 'Read clipboard'
shortcut (on Android 7.1 to 9).

The problem appears to be related to issue #27, which causes an erroneous
text-to-speech initialization failure on Android 11.  Are you also having
that problem?  If so, it is fixed in TTS Util version 4.0.1, which should
be available from the Google Play or F-Droid store in the next few days.

There are some other cases where this behaviour can occur, e.g. if there is
a legitimate text-to-speech initialization failure.  I will add fixes for
those cases in TTS Util version 4.0.2.

**Comment by kudlav** [comment]
Unfortunately, version 4.0.1 has still behavior.
App can see TTS engine and available languages and the app works.
I think the problem is related to too long strings.
When I paste the text into textbox, it's not read whole, it stops reading after few minutes.

**Comment by Danesprite** [comment]
Ah, you're right; I see it is still a problem in v4.0.1.  It seemed to be working for me earlier, but I had been testing with the wrong version.

This problem shouldn't occur if text is read/synthesised in *TTS Util* first, so that text-to-speech is initialized.  Of course, it will stop working again if your device kills the application in order to free memory.  In any case, the problem will be fixed in v4.0.2.

If you are having trouble with longer text not being read to completion, then perhaps the fault lies with the text-to-speech engine?  I've noticed this behaviour with some of them.  Which engine are you using with *TTS Util*?  Alternatively, try changing the application's *Silent Utterances* -> *Line Endings* setting to "Let the engine decide."

**Comment by Danesprite** [comment]
Hello @kudlav,

This issue is resolved in version 4.0.2, now available for download from the F-Droid store.  It is also available from the Google Play store, just not in Czechia.
