### ISSUE TITLE
Crashes when Reading File

### ISSUE THREAD

**Issue by richwalm** [Danesprite/tts-util-app#7]
Hi Dane, congratulations on releasing version 2.0.

Unfortunately, I'm unable to have it 'Read from File'. Doesn't seem to matter which TXT file I choose, short or long, it crashes with the following;
https://imgur.com/a/mLVZCde
As my phone doesn't allow me to select the crash report text, I'm unable to upload it as plain text. If I find a way of extracting it, I'll include it.

I'm running 2.0 from the GitHub releases page, using a Mi 9T phone running Android 10.

Let me know if you need any further information.

**Comment by Danesprite** [comment]
Hi @richwalm,

Thanks for trying out TTS Util version 2.0 and submitting this report! I wasn't expecting anyone to try it out so quickly!

It doesn't look like this bug will be difficult to fix. Just a silly assumption on my part that Android would only yield non-null strings for file properties. I should be able to release a new version in the next few days.

**Comment by Danesprite** [comment]
This should be fixed in [version 2.0.1](https://github.com/Danesprite/tts-util-app/releases/tag/v2.0.1) now. I have uploaded a new APK. I will try to get the F-Droid version updated soon.

I will say that I was unable to reproduce the bug myself. It probably just doesn't occur when using the default file manager app. Please let me know if it's still broken.

**Comment by richwalm** [comment]
Hi Danesprite, v2.0.1 is working fine. Thanks.

**Comment by Danesprite** [comment]
Great, I'm glad I could fix the problem! I hope you find the app useful :-)
