### ISSUE TITLE
App doesn't register as TTS engine

### ISSUE THREAD

**Issue by Oymate** [Danesprite/tts-util-app#8]

**Comment by Danesprite** [comment]
Hello @Oymate,

The app doesn't register as a text-to-speech engine in the Android system settings because it is not itself a text-to-speech engine. Instead, it utilises an installed text-to-speech engine app for its functionality. It *requires* a separate text-to-speech engine be installed in order to function. I will make this clearer on the store pages, in the readme file and on my website.
